version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - evolution_data:/app/evolution_data
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: ["node", "dist/src/main.js"]

  redis:
    image: redis:7-alpine
    container_name: evolution-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data


  db:
    image: postgres:15-alpine
    container_name: evolution-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  evolution_data:
  postgres_data:
  redis_data:

